// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Y2S1_INC_Compliance_proj.Data;

#nullable disable

namespace Y2S1_INC_Compliance_proj.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250719085133_SchoolYear")]
    partial class SchoolYear
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Finals.Models.SemesterModel", b =>
                {
                    b.Property<string>("SemesterId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SchoolYearId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SemesterId");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("SemesterModel");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.AdminModel", b =>
                {
                    b.Property<string>("AdminID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("AdminID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("AdminModels");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.SchoolYearModel", b =>
                {
                    b.Property<string>("SchoolYearId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRegistrationOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("SchoolYearId");

                    b.ToTable("SchoolYearModel");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.StudentModel", b =>
                {
                    b.Property<string>("StudentID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("StudentID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentModels");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.TeacherModel", b =>
                {
                    b.Property<string>("TeacherID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("TeacherID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("TeacherModels");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.TestModel", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID");

                    b.ToTable("TestModels", (string)null);
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.UserModel", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserRole")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("UserModels");
                });

            modelBuilder.Entity("Finals.Models.SemesterModel", b =>
                {
                    b.HasOne("Y2S1_INC_Compliance_proj.Models.SchoolYearModel", "SchoolYear")
                        .WithMany("Semesters")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.AdminModel", b =>
                {
                    b.HasOne("Y2S1_INC_Compliance_proj.Models.UserModel", "User")
                        .WithOne()
                        .HasForeignKey("Y2S1_INC_Compliance_proj.Models.AdminModel", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.StudentModel", b =>
                {
                    b.HasOne("Y2S1_INC_Compliance_proj.Models.UserModel", "User")
                        .WithOne()
                        .HasForeignKey("Y2S1_INC_Compliance_proj.Models.StudentModel", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.TeacherModel", b =>
                {
                    b.HasOne("Y2S1_INC_Compliance_proj.Models.UserModel", "User")
                        .WithOne()
                        .HasForeignKey("Y2S1_INC_Compliance_proj.Models.TeacherModel", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.SchoolYearModel", b =>
                {
                    b.Navigation("Semesters");
                });
#pragma warning restore 612, 618
        }
    }
}
