// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Finals.Data;

#nullable disable

namespace Finals.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250727030432_ClassSection")]
    partial class ClassSection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClassSectionModelUserModel", b =>
                {
                    b.Property<string>("ClassSectionModelSectionID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StudentsUserID")
                        .HasColumnType("varchar(50)");

                    b.HasKey("ClassSectionModelSectionID", "StudentsUserID");

                    b.HasIndex("StudentsUserID");

                    b.ToTable("ClassSectionModelUserModel");
                });

            modelBuilder.Entity("Finals.Models.ClassSectionEditLog", b =>
                {
                    b.Property<string>("LogId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EditDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("EditType")
                        .HasColumnType("int");

                    b.Property<string>("EditedByUserId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("LogId");

                    b.HasIndex("EditedByUserId");

                    b.HasIndex("SectionId");

                    b.ToTable("ClassSectionsEdits");
                });

            modelBuilder.Entity("Finals.Models.ClassSectionModel", b =>
                {
                    b.Property<string>("SectionID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SectionID");

                    b.ToTable("ClassSections", (string)null);
                });

            modelBuilder.Entity("Finals.Models.ClassSectionTransitionModel", b =>
                {
                    b.Property<string>("TransitionId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FromSectionId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ToSectionId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<double>("TransitionPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("double");

                    b.HasKey("TransitionId");

                    b.HasIndex("FromSectionId");

                    b.HasIndex("ToSectionId");

                    b.ToTable("ClassSectionTransitions", (string)null);
                });

            modelBuilder.Entity("Finals.Models.ProgramModel", b =>
                {
                    b.Property<string>("ProgramId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastEditorId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProgramDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ProgramId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("LastEditorId");

                    b.ToTable("programmodel", (string)null);
                });

            modelBuilder.Entity("Finals.Models.ProgramModel_Edits", b =>
                {
                    b.Property<string>("Edit_ID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Edit")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("EditedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Edit_ID");

                    b.HasIndex("EditorId");

                    b.HasIndex("ProgramId");

                    b.ToTable("programmodel_edits", (string)null);
                });

            modelBuilder.Entity("Finals.Models.SemesterModel", b =>
                {
                    b.Property<string>("SemesterId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SchoolYearId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SemesterId");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.AdminModel", b =>
                {
                    b.Property<string>("AdminID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("AdminID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("AdminModels");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.SchoolYearModel", b =>
                {
                    b.Property<string>("SchoolYearId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRegistrationOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("SchoolYearId");

                    b.ToTable("SchoolYearModels");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.StudentModel", b =>
                {
                    b.Property<string>("StudentID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("StudentID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentModels");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.TeacherModel", b =>
                {
                    b.Property<string>("TeacherID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("TeacherID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("TeacherModels");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.TestModel", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID");

                    b.ToTable("TestModels", (string)null);
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.UserModel", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserRole")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("UserModels");
                });

            modelBuilder.Entity("ClassSectionModelUserModel", b =>
                {
                    b.HasOne("Finals.Models.ClassSectionModel", null)
                        .WithMany()
                        .HasForeignKey("ClassSectionModelSectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Y2S1_INC_Compliance_proj.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("StudentsUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Finals.Models.ClassSectionEditLog", b =>
                {
                    b.HasOne("Y2S1_INC_Compliance_proj.Models.UserModel", "EditedByUser")
                        .WithMany()
                        .HasForeignKey("EditedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finals.Models.ClassSectionModel", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EditedByUser");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Finals.Models.ClassSectionTransitionModel", b =>
                {
                    b.HasOne("Finals.Models.ClassSectionModel", "FromSection")
                        .WithMany("IncomingTransition")
                        .HasForeignKey("FromSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finals.Models.ClassSectionModel", "ToSection")
                        .WithMany()
                        .HasForeignKey("ToSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromSection");

                    b.Navigation("ToSection");
                });

            modelBuilder.Entity("Finals.Models.ProgramModel", b =>
                {
                    b.HasOne("Y2S1_INC_Compliance_proj.Models.UserModel", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Y2S1_INC_Compliance_proj.Models.UserModel", "LastEditedBy")
                        .WithMany()
                        .HasForeignKey("LastEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastEditedBy");
                });

            modelBuilder.Entity("Finals.Models.ProgramModel_Edits", b =>
                {
                    b.HasOne("Y2S1_INC_Compliance_proj.Models.UserModel", "EditedBy")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finals.Models.ProgramModel", "ProgramEdited")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EditedBy");

                    b.Navigation("ProgramEdited");
                });

            modelBuilder.Entity("Finals.Models.SemesterModel", b =>
                {
                    b.HasOne("Y2S1_INC_Compliance_proj.Models.SchoolYearModel", "SchoolYear")
                        .WithMany("Semesters")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.AdminModel", b =>
                {
                    b.HasOne("Y2S1_INC_Compliance_proj.Models.UserModel", "User")
                        .WithOne()
                        .HasForeignKey("Y2S1_INC_Compliance_proj.Models.AdminModel", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.StudentModel", b =>
                {
                    b.HasOne("Y2S1_INC_Compliance_proj.Models.UserModel", "User")
                        .WithOne()
                        .HasForeignKey("Y2S1_INC_Compliance_proj.Models.StudentModel", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.TeacherModel", b =>
                {
                    b.HasOne("Y2S1_INC_Compliance_proj.Models.UserModel", "User")
                        .WithOne()
                        .HasForeignKey("Y2S1_INC_Compliance_proj.Models.TeacherModel", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finals.Models.ClassSectionModel", b =>
                {
                    b.Navigation("IncomingTransition");
                });

            modelBuilder.Entity("Y2S1_INC_Compliance_proj.Models.SchoolYearModel", b =>
                {
                    b.Navigation("Semesters");
                });
#pragma warning restore 612, 618
        }
    }
}
